# Generated by Django 5.0.5 on 2024-06-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
